gitRepoUrl = "https://github.com/fuzzy-bit/Litework"
gitSourceBranch = "master"


[[classOrder]]
classes = ["Litework"]

[[classOrder]]
section = "Network"
classes = ["Network", "Communicator"]

[[classOrder]]
section = "Vendor"
classes = ["Signal"]


[docusaurus]
tagline = "Modular & Lightweight Roblox Framework"